"
" rockettman vim
"

" Vundle & Plugins {{{
set nocompatible        " turn off vi compatibility
filetype off            " just for vundle configuration

" add Vundle to the runtime path and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Plugins {{{
Plugin 'Valloric/YouCompleteMe'         " code complete
Plugin 'scrooloose/nerdtree'            " file tree
Plugin 'jistr/vim-nerdtree-tabs'        " cleaner usage of NERDTree
Plugin 'kien/ctrlp.vim'                 " Ctrl-p fuzzy search
Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
Plugin 'tmhedberg/SimpylFold'           " smarter folding (collapse blocks of code)
" }}}

call vundle#end()           " required
filetype plugin indent on   " required

" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ

" }}}
" Standard Options {{{
set encoding=utf-8      " use utf-8 charater encoding in vim buffers
let mapleader=","       " <leader> is comma
" }}}
" Editor {{{
set tabstop=4           " number of rendered spaces per TAB
set shiftwidth=0        " number of spaces used for <<, >>  0 means use tabstop value
set softtabstop=-1      " number of spaces inserted for TAB when editing, -1 means use shiftwidth value
set expandtab           " tabs are spaces
set autoindent          " copy indent from current line when starting new line
set showmatch           " highlight matching [{()}]
set nobackup            " I tend to save obsessively so yeeha

" Movement {{{
set backspace=2         " allow backspace over everything in insert mode
set scrolloff=7         " don't let the cursor get too close to the top/bottom

" move vertically by visual line
nnoremap j gj
nnoremap k gk
" }}}
" Searching {{{
set incsearch           " search as characters are entered
set hlsearch            " highlight all matches
set ignorecase          " do case insensitive search by default

" turn off search highlight with easy sequence
nnoremap <leader><space> :nohlsearch<CR>
" }}}
" Folding {{{
set foldenable          " enable folding
set foldlevelstart=10   " open most folds by default
set foldnestmax=10      " at most x levels of folding, keeps it getting too crazy
set foldmethod=indent   " fold based on indent level

" <space> open/closes folds
noremap <space> za
" }}}

" }}}
" UI Config {{{
set number              " show line numbers
set showcmd             " show command in bottom bar
set laststatus=2        " always have status bar
set ruler               " show position in file in bottom
set wildmenu            " visual autocomplete for command menu
set lazyredraw          " redraw only when we need to

" Colors {{{
syntax enable           " enable syntax processing
" }}}

" }}}


" Setup section structure for this file
set modelines=1
" vim:foldmethod=marker:foldlevel=0
